export const USER_ACTION_TYPES = {
	FETCH_USER_LIST: "FETCH_USER_LIST",
	SEARCH_USER: "SEARCH_USER",
	REFRESH_USER_LIST: "REFRESH_USER_LIST",
};

export const PROFILE_ACTION_TYPES = {
	FETCH_PROFILE: "FETCH_PROFILE",
};
