export const USER_ACTION_TYPES = {
	FETCH_USER_LIST: "FETCH_USER_LIST",
	SEARCH_USER: "SEARCH_USER",
	REFRESH_USER_LIST: "REFRESH_USER_LIST",
};

export const PROFILE_ACTION_TYPES = {
	FETCH_PROFILE: "FETCH_PROFILE",
	FETCH_GAME_HISTORY: "FETCH_GAME_HISTORY",
};

export const GAME_ACTION_TYPES = {
	FETCH_GAME_LIST: "FETCH_GAME_LIST",
	REFRESH_GAME_LIST: "REFRESH_GAME_LIST",
};

export const GAME_REPLAY_ACTION_TYPES = {
	FETCH_GAME_REPLAY: "FETCH_GAME_REPLAY",
	SET_STEP: "SET_STEP",
};
